library(readxl)
library(wordcloud)
library(shiny)
library(ggplot2)
library(leaflet)
library(plotly)
library(shinythemes)
library(shinyWidgets)
library(wordcloud)
my_data <- read_excel("DDWC-280015.xls")
lat <- mean(my_data$Latitude)
lon <- mean(my_data$Longitude)
total <- read.csv("data.csv")
area_name <- sort(unique(my_data$Area_name))
caste_name <- sort(unique(total$CASTE_NAME))